baseURL = "http://jacsaddict.github.io"
languageCode = "en-us"
title = "jacsaddict"
theme = "tale"
Paginate = 10
DefaultContentLanguage = "tw"
defaultContentLanguageInSubdir = true
disqusShortname = "jacsaddict-github"
googleAnalytics = "UA-130193510-3"
[Author]
    name = "jacsaddict"
    
[params]
  githubName = "jacsaddict"

[languages]
  [languages.tw]
    contentDir = "content/tw"
    languageName = "繁體中文"
    weight = 1
  
  [languages.en]
    contentDir = "content/en"
    languageName = "En"
    weight = 2